name: par-hp
channels:
  - default
  - pytorch
dependencies:
  - python>=3.9
  - pytorch>=1.10.0
  - torchvision>=0.11.1
  - cudatoolkit=11.3
  - tensorflow>=2.4.1
  - numpy>=1.21.2
  - pandas>=1.3.4
  - scipy>=1.7.1
  - tabulate>=0.8.9
  - matplotlib>=3.4.3
  - scikit-learn
  - notebook
