python baseline_trainer.py \
    -d rap \
    --gpu-devices 1 \
    --max-epoch 180 \
    --stepsize 60 120 \
    --eval-split test \
    --save-experiment=/net/merkur/storage/deeplearning/users/floluc/baseline_rap/ \
    --loss-func scel \
    --f1-calib \
    --f1-calib-split val \
    --use-macc \