python realistic_predictor_trainer.py \
    -d pa100k \
    --gpu-devices 0 \
    --max-epoch 360 \
    --eval-split val \
    --save-experiment=/net/merkur/storage/deeplearning/users/floluc/baseline_pa/ \
    --stepsize 120 240 \
    --loss-func deepmar \
    --use-macc \
    --no-hp-feedback \
    --random-translation \
    --color-jitter
