python realistic_predictor_trainer.py \
    -d pa100k \
    --gpu-devices 0 \
    --max-epoch 180 \
    --stepsize 60 120 \
    --train-batch-size 8 \
    --eval-split test \
    --rejector-thresholds-split val \
    --save-experiment=/net/merkur/storage/deeplearning/users/floluc/baseline_pa/ \
    --loss-func scel \
    --no-hp-feedback \
