python baseline_trainer.py \
    -d rap \
    --gpu-devices 1 \
    --max-epoch 180 \
    --stepsize 60 120 \
    --random-translation \
    --color-jitter \
    --eval-split val \
    --save-experiment=/net/merkur/storage/deeplearning/users/floluc/baseline_rap/ \
    --loss-func deepmar \
    --use-macc \
    --train-val \