python realistic_predictor_trainer.py \
    -d rap \
    --gpu-devices 3 \
    --eval-split val \
    --save-experiment=/net/merkur/storage/deeplearning/users/floluc/baseline_rap/ \
    --load-weights=2019-09-11_18-32-31_checkpoint.pth.tar \
    --evaluate \
    --use-macc \
    --rejector macc \
    --max-rejection-quantile 0.25 \
    --rejection-threshold 0.4
    --use-confidence
