python realistic_predictor_trainer.py \
    -d rap \
    --gpu-devices 0 \
    --eval-split test \
    --save-experiment=/net/merkur/storage/deeplearning/users/floluc/baseline_rap/ \
    --load-weights=2019-10-09_14-38-09_checkpoint.pth.tar \
    --evaluate \
    --use-macc \
    --rejector threshold \
    --max-rejection-quantile 0.25 \
    --rejection-threshold 0.20
    --use-confidence
