python realistic_predictor_trainer.py \
    -d peta \
    --gpu-devices 0 \
    --eval-split val \
    --save-experiment=/net/merkur/storage/deeplearning/users/floluc/baseline_peta/ \
    --load-weights=2019-07-01_19-07-30_checkpoint.pth.tar \
    --evaluate \
    --use-macc \
    --f1-calib \
    --num-save-hard 20 \
    --num-save-easy 20 \
    --hard-att personalMale \
    --reject-hard-portion 0.3
